# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            TurkishArmy
tagline:          it's for pro's
description:      "Bu site server 30'da bulunan ittifakimizi gladiatus oyuncularina tanitmak, ittifak uyelerine bilgi vermek ve gladiatus ile ilgili icerik uretmek icin yayindadir."
url:              https://s30-tr.gladiatus.gameforge.com/game/index.php?mod=guild&submod=forumGladiatorius&sh=e44d8ca4b22a3113c6bc95cea4d5ae72
baseurl:          /

author:
  name:           'Karlo Espiritu'
  url:            https://twitter.com/karloespiritu

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/t-army/t-army.github.io
